### ISSUE TITLE
Copy doesn't work sometimes

### ISSUE THREAD

**Issue by sirgru** [SrTobi/code-clip-ring#10]
Sometimes Copy operation is not registered. Can't quite pinpoint it yet, but I notice it on the 1st "copy whole line" operation when I open the file sometimes, though it may be happening at other times too.

**Comment by sirgru** [comment]
I'm on Windows 8.1, VS Code 1.25.1

**Comment by sirgru** [comment]
Could it be that another command editor.action.clipboardCopyAction was causing "race conditions" with this extension, hence the intermittent problems? I just unbounded that from Ctrl + C and couldn't reproduce the error again (still not sure if it will reappear).

**Comment by rms95** [comment]
Seems I have the same issue, however I have text that you can read :)

> Command failed: C:\Users\me\.vscode\extensions\sirtobi.code-clip-ring-0.1.1\node_modules\clipboardy\fallbacks\windows\clipboard_x86_64.exe --paste
> thread 'main' panicked at 'Error: Could not paste from clipboard: Error { repr: Os { code: 0, message: "The operation completed successfully." } }', src\libcore\result.rs:906:4
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

This warning shows up bottomleft, then copy does not execute, copy via context menu does work though.

**Comment by timiles** [comment]
Yep, I was getting that error on paste, but I believe it's to do with the clipboardy dependency rather than code-clip-ring itself. I raised an issue on the clipboardy project too: https://github.com/sindresorhus/clipboardy/issues/42

**Comment by SrTobi** [comment]
Hey guys. Thanks for escalating this to clipboardy. I'm currently on vacation so I can't do anything. Hopefully they can fix the error, then I will update the extension when I'm back.

**Comment by SrTobi** [comment]
Good news guys! The vscode team finally decided to add a clipboard api... as I understand it, this will be only available in the insider version... i will look into this shortly.

Announcement: https://code.visualstudio.com/updates/v1_29#_clipboard-api

**Comment by SrTobi** [comment]
So, I removed clipboardy as a dependency and moved to the new vs code clipboard api. @timiles @sirgru @rms95, please test it out. Would be nice to hear if the errors are gone now.
