### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by shridharkalagi** [SrTobi/code-clip-ring#15]
This extension is not working on Mac 10.12.6 . Can you help?

**Comment by SrTobi** [comment]
Hi. That is probably a problem with the library that I use to access the clipboard. Fortunately the vscode team decided to make the clipboard accessible via an api. As I understand it, this api is currently only accessible in the insider version but will be available in the normal version shortly. I will look into this shortly.

**Comment by SrTobi** [comment]
@shridharkalagi I updated the extension. It uses the new vscode 1.30 clipboard api. Can you try it again?

**Comment by ivan-nejezchleb** [comment]
Similar issue here. 
in last few days shortcut used for accessing multiclipboard shows
"command 'clipring.selectAndPasteRingItem' not found"
Plugin says it needs reload of VSCode, but it doesn't help
Mac 10.12.6
VSCode Version 1.30.2 (1.30.2)

**Comment by SrTobi** [comment]
Can you tell me the version of the extension? You can see it in the list of enabled extensions next to the name of the extension?

**Comment by SrTobi** [comment]
Ok... there was a problem with the engine version in the extension. I fixed that and uploaded a new version (`0.3.1`). Try to update the extension and please report if the error is still there.

**Comment by ivan-nejezchleb** [comment]
my version of Clipboard Ring 0.3.0, but I see u have already 0.3.1. I will try it. thx

**Comment by ivan-nejezchleb** [comment]
Ok, I updated extension to 0.3.1 and it works again. Thank you

**Comment by SrTobi** [comment]
ok, perfect :+1:
