### ISSUE TITLE
Don't select pasted after `Select and paste Ring Item`;

### ISSUE THREAD

**Issue by eof273** [SrTobi/code-clip-ring#17]
Is it possible to add option for don't select pasted text after `Select and paste Ring Item` command (like after default paste)?

P.S.: Thanks, awesome extension!

**Comment by SrTobi** [comment]
I see what you mean. Would a config option be enough? Not sure if I want to add a new command...

Alternatively you could also use the `right key` to deselect code :smile: that's only one more key stroke xD

**Comment by eof273** [comment]
`Would a config option be enough?`
Yeah, of course! It would be great!
I'm using <kbd>→</kbd> a few hours, and I'm already tired :D

**Comment by SrTobi** [comment]
:smiley: I added an option `clipring.selectTextAfterPasteFromMenu`. Set it to `false` and tell me if it works and if it's enough.

**Comment by eof273** [comment]
Awesome! Exactly what I wanted :+1: 
Thanks.
