### ISSUE TITLE
Does not work with non QWERTY keyboard layouts

### ISSUE THREAD

**Issue by fourpastmidnight** [SrTobi/code-clip-ring#3]
I use the Dvorak (US) Keyboard layout and I could no longer copy using <kbd>CTRL+I</kbd> (where <kbd>I</kbd> on the QWERTY keyboard layout is a <kbd>C</kbd> on the Dvorak keyboard. Once I disabled this extension, copying worked once again.

**Comment by SrTobi** [comment]
Yeah, this extension overwrites the default shortcuts for copy and cut (to capture the selected text and move it to the clipboard ring).

But it does not copy anything? Which OS are you using?
