### ISSUE TITLE
Copies something else than I selected

### ISSUE THREAD

**Issue by eitland** [SrTobi/code-clip-ring#6]
When I select some text and press ctrl-c it frequently selects the line above or something else it seems.

Possibly related: I run the Insiders version of Visual Studio Code.

Workaround: Ususally if I press ctrl-c twice it works.

(I know this sounds weird and if anyone has a good tool to quickly make a recording like the ones in the marketplace page then I might try to capture it.)

**Comment by SrTobi** [comment]
Weird indeed. Do you are under windows or Linux or mac?
Under linux I used https://github.com/phw/peek
On windows I used this: http://www.screentogif.com/
