### ISSUE TITLE
Add Option: Disable Copy null to Clipboard

### ISSUE THREAD

**Issue by cycle4passion** [SrTobi/code-clip-ring#7]
When clipboard is loaded with something, I commonly try to paste and accidentally copy (with nothing selected) writing null to clipboard, and prior to use of this extension losing my copied text. I cannot think of an instance where a blank clipboard ring item would be helpful.

**Comment by SrTobi** [comment]
When you have nothing selected and press copy the current line is copied. If that line is empty a single line break character is copied to the clipboard. Do you suggest that the extension does not store single line breaks in the ring?
