### ISSUE TITLE
Clipboard stopped working with warning

### ISSUE THREAD

**Issue by leotok** [SrTobi/code-clip-ring#8]
- Extension Name: code-clip-ring
- Extension Version: 0.0.4
- OS Version: Linux x64 4.13.0-26-generic
- VSCode version: 1.19.1

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 8,
		"activateCallTime": 1,
		"activateResolvedTime": 0,
		"activationEvent": "onCommand:clipring.copyToRing"
	}
}
```
Clipboard stopped working and VSCode is showing me a warning when I press Ctrl + C or any other clipboard command:
`spawn xclip ENOENT`

**Comment by SrTobi** [comment]
Do you have [xclip](https://wiki.ubuntuusers.de/xclip/) installed?
