### ISSUE TITLE
Multiline Ring item display problem

### ISSUE THREAD

**Issue by sirgru** [SrTobi/code-clip-ring#9]
When selecting multiple lines, and opening "Select and paste ring item", the lines are not displayed properly. 
I think the extension should take only the 1st line of the multiline copy and display that in the dropdown, if the height of items cannot be extended.

**Comment by SrTobi** [comment]
Hi, thanks for reporting. I fixed it. I also changed the underlying cope/paste library. Please test if it works and if you like the way the items are presented

**Comment by sirgru** [comment]
Thank you, it works now. 
There seems to be a little enter/return icon on lines that are short but are not multiline select. Shouldn't that be happening only for multiline items where the first line is short?

**Comment by sirgru** [comment]
Yes, it works now. Thanks!
Currently for multiline selection there is the first line and if it can fit the return icon, and the same for following lines. I'm OK with this style of display. 
However, would it be possible for items in the quickbar to be multiline themselves? One idea would be to display for example first 3 lines for multiline selection rather than it being one line, of course selected as one. I got used to Clipboard History extension from full Visual Studio and I'm trying to emulate that behavior.
Another thing would be to number the items in the clip ring so we don't have to use arrows to select items we want, we'd press number to fuzzy search to it and Enter.

**Comment by SrTobi** [comment]
Hmm, don't know to be honest. I would have to look into it. The idea with the numbers is good as well, but could you open two new separate issues for them and we can mark them as feature request. I believe this one is solved.
